export enum AuthErrorCode {
  USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "AUTH_USER_ALREADY_EXISTS",
  USER_NOT_VERIFIED = "AUTH_USER_NOT_VERIFIED",
  USER_BLOCKED = "AUTH_USER_BLOCKED",

  INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  INVALID_ACCESS = "AUTH_INVALID_ACCESS",

  INVALID_OTP = "AUTH_INVALID_OTP",
  OTP_NOT_FOUND = "AUTH_OTP_NOT_FOUND",

  INVALID_RESET_TOKEN = "AUTH_INVALID_RESET_TOKEN",
}
