import { HospitalVerificationRepositoryImpl } from "../infrastructure/repositories/HospitalVerification.repository";
import { MongoUserRepository } from "../infrastructure/repositories/user.repo.mongo";
import { HospitalRepositoryImpl } from "../infrastructure/repositories/Hospital.repository";
// import { HospitalSpecialtyModel } from "../infrastructure/database/mongo/models/HospitalSpeciality.model";
import { HospitalSpecialtyRepositoryImpl } from "../infrastructure/repositories/HospitalSpeciality.repo";
import { DoctorRepositoryImpl } from "../infrastructure/repositories/Doctor.repository";
import { MongoDoctorAvailabilityRepository } from "../infrastructure/repositories/DoctorAvailability.Repository";
import { DoctorAppointmentRepository } from "../infrastructure/repositories/DoctorAppointment.repository";
import { DoctorSearchMongoRepository } from "../infrastructure/repositories/DoctorSearch.repository";
import { DoctorReviewRepository } from "../infrastructure/repositories/DoctorReviewRepository";
import { PatientProfileRepository } from "../infrastructure/repositories/PatientProfileRepository";
import { MedicalRecordRepository } from "../infrastructure/repositories/MedicalRecordRepository";
import { ConsultationRepository } from "../infrastructure/repositories/ConsultationRepository";
import { WalletRepository } from "../infrastructure/repositories/WalletRepository";
import { SubscriptionPlanRepository } from "../infrastructure/repositories/SubscriptionPlanRepository";
import { HospitalSubscriptionRepository } from "../infrastructure/repositories/HospitalSubscriptionRepository";
import { SuperAdminDashboardRepo } from "../infrastructure/repositories/SuperAdminDashboardRepo";
import { HospitalDashboardMongoRepository } from "../infrastructure/repositories/HospitalDashboard.repository";
import { DoctorDashboardMongoRepository } from "../infrastructure/repositories/DoctorDashboard.Repository";
import { PatientDashboardMongoRepository } from "../infrastructure/repositories/PatientDashboardMongoRepository";
import { HospitalLabOrderRepository } from "../infrastructure/repositories/HospitalLabOrderRepository";
// import { NotificationRepository } from "../infrastructure/repositories/notification/NotificationRepository";

export const mongoUserRepository = new MongoUserRepository();
export const hosptialVerficatinRepo = new HospitalVerificationRepositoryImpl();
export const hosptialRepository = new HospitalRepositoryImpl();
export const hospitalSpecialityRepo = new HospitalSpecialtyRepositoryImpl();
export const doctorRepo = new DoctorRepositoryImpl();
export const doctorAvailabilityRepository = new MongoDoctorAvailabilityRepository();
export const doctorAppointmentRepository = new DoctorAppointmentRepository();
export const doctorSearchMongoRepository = new DoctorSearchMongoRepository();
export const doctorReviewRepository = new DoctorReviewRepository();
export const patientProfileRepository = new PatientProfileRepository();
export const medicalRecordRepository = new MedicalRecordRepository();
// export const notificationRepo = new NotificationRepository();
export const consultationRepo = new ConsultationRepository();
export const walletRepo = new WalletRepository();
export const subscriptionPlanRepository = new SubscriptionPlanRepository();
export const hospitalSubscriptionRepository = new HospitalSubscriptionRepository();
export const superAdminDashboardRepo = new SuperAdminDashboardRepo();
export const hospitalDashboardRepository = new HospitalDashboardMongoRepository();
export const doctorDashboardRepository = new DoctorDashboardMongoRepository();
export const patientDashboardRepository = new PatientDashboardMongoRepository();
export const hospitalLabOrderRepository = new HospitalLabOrderRepository();
