import { HospitalVerificationRepositoryImpl } from "../infrastructure/repositories/HospitalVerification.repository";
import { MongoUserRepository } from "../infrastructure/repositories/user.repo.mongo";
import { HospitalRepositoryImpl } from "../infrastructure/repositories/Hospital.repository";
// import { HospitalSpecialtyModel } from "../infrastructure/database/mongo/models/HospitalSpeciality.model";
import { HospitalSpecialtyRepositoryImpl } from "../infrastructure/repositories/HospitalSpeciality.repo";
import { DoctorRepositoryImpl } from "../infrastructure/repositories/Doctor.repository";
import { MongoDoctorAvailabilityRepository } from "../infrastructure/repositories/DoctorAvailability.Repository";
import { DoctorAppointmentRepository } from "../infrastructure/repositories/DoctorAppointment.repository";
import { DoctorSearchMongoRepository } from "../infrastructure/repositories/DoctorSearch.repository";
import { DoctorReviewRepository } from "../infrastructure/repositories/DoctorReviewRepository";
import { PatientProfileRepository } from "../infrastructure/repositories/PatientProfileRepository";
import { MedicalRecordRepository } from "../infrastructure/repositories/MedicalRecordRepository";
import { ConsultationRepository } from "../infrastructure/repositories/ConsultationRepository";
// import { NotificationRepository } from "../infrastructure/repositories/notification/NotificationRepository";

export const mongoUserRepository = new MongoUserRepository();
export const hosptialVerficatinRepo = new HospitalVerificationRepositoryImpl();
export const hosptialRepository = new HospitalRepositoryImpl();
export const hospitalSpecialityRepo = new HospitalSpecialtyRepositoryImpl();
export const doctorRepo = new DoctorRepositoryImpl();
export const doctorAvailabilityRepository = new MongoDoctorAvailabilityRepository();
export const doctorAppointmentRepository = new DoctorAppointmentRepository();
export const doctorSearchMongoRepository = new DoctorSearchMongoRepository();
export const doctorReviewRepository = new DoctorReviewRepository();
export const patientProfileRepository = new PatientProfileRepository();
export const medicalRecordRepository = new MedicalRecordRepository();
// export const notificationRepo = new NotificationRepository();
export const consultationRepo = new ConsultationRepository();
